In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'/Users/vishwa/Desktop/EEG/data2.csv')

In [3]:
df.head()

,name,hearts,TRP1,Question no,TRP2,TRP3,TRP4,TRP11,TRP12,ARP1,...,TPA12,TPA2,TPA3,TPA4,TRPA1,TRPA11,TRPA12,TRPA2,TRPA3,TRPA4
0,gautam,5,0.212639,13,0.103793,0.188616,0.044259,0.070351,0.116575,0.030169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,gautam,5,0.030412,11,0.026436,0.028877,0.028846,0.027433,0.021008,0.029668,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,gautam,5,0.109850,39,0.107796,0.107742,0.086027,0.095648,0.127854,0.008424,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,gautam,5,0.061227,38,0.021576,0.062308,0.038776,0.053106,0.036498,0.050657,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,gautam,5,0.015245,10,0.038250,0.015673,0.010675,0.043753,0.021831,0.015099,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns

Index(['name', 'hearts', 'TRP1', 'Question no', 'TRP2', 'TRP3', 'TRP4',
       'TRP11', 'TRP12', 'ARP1', 'ARP2', 'ARP3', 'ARP4', 'ARP11', 'ARP12',
       'BRP1', 'BRP2', 'BRP3', 'BRP4', 'BRP11', 'BRP12', 'APA1', 'APA2',
       'APA3', 'APA4', 'APA5', 'APA6', 'APA7', 'APA8', 'APA9', 'APA10',
       'APA11', 'APA12', 'APA13', 'APA14', 'APA15', 'APA16', 'APA17', 'APA18',
       'APA19', 'APA20', 'APA21', 'BRPA2', 'BRPA3', 'BRPA4', 'TPA1', 'TPA11',
       'TPA12', 'TPA2', 'TPA3', 'TPA4', 'TRPA1', 'TRPA11', 'TRPA12', 'TRPA2',
       'TRPA3', 'TRPA4'],
      dtype='object')

In [5]:

df.shape

(1096, 57)

In [6]:
df[['Question no','hearts','TPA1']][100:200]

     Question no  hearts  TPA1
100            1       4   NaN
101            6       4   NaN
102           33       4   NaN
103           26       4   NaN
104           30       4   NaN
105           34       4   NaN
106           20       4   NaN
107           36       4   NaN
108           23       4   NaN
109           12       4   NaN
110           11       4   NaN
111           38       4   NaN
112           10       4   NaN
113           15       4   NaN
114           17       4   NaN
115            8       4   NaN
116            9       4   NaN
117           42       4   NaN
118           43       4   NaN
119           40       4   NaN
120           33       4   NaN
121           32       4   NaN
122           24       4   NaN
123           36       4   NaN
124           23       4   NaN
125           14       4   NaN
126            9       4   NaN
127           42       4   NaN
128            4       4   NaN
129            7       4   NaN
..           ...     ...   ...
170           27       4   NaN
171           26       4   NaN
172           25       4   NaN
173           11       4   NaN
174           10       4   NaN
175           28       4   NaN
176            4       4   NaN
177            5       4   NaN
178           26       4   NaN
179           25       4   NaN
180           20       4   NaN
181           37       4   NaN
182           42       4   NaN
183           40       4   NaN
184            6       4   NaN
185           27       4   NaN
186           30       4   NaN
187           34       4   NaN
188           36       4   NaN
189           13       4   NaN
190           10       4   NaN
191           28       4   NaN
192           14       4   NaN
193           15       4   NaN
194           42       4   NaN
195            4       4   NaN
196            5       4   NaN
197           43       4   NaN
198           27       4   NaN
199           26       4   NaN

[100 rows x 3 columns]

In [7]:
list= ['APA1', 'APA11',
       'APA12', 'APA2', 'APA3', 'APA4', 'ARPA1', 'ARPA11', 'ARPA12', 'ARPA2',
       'ARPA3', 'ARPA4', 'BPA1', 'BPA11', 'BPA12', 'BPA2', 'BPA3', 'BPA4',
       'BRPA1', 'BRPA11', 'BRPA12', 'BRPA2', 'BRPA3', 'BRPA4', 'TPA1', 'TPA11',
       'TPA12', 'TPA2', 'TPA3', 'TPA4', 'TRPA1', 'TRPA11', 'TRPA12', 'TRPA2',
       'TRPA3', 'TRPA4']
len(list)
list[0]

'APA1'

In [8]:
#for i in range(len(list)):
df.fillna(df.mean()['TPA1'])

,name,hearts,TRP1,Question no,TRP2,TRP3,TRP4,TRP11,TRP12,ARP1,...,TPA12,TPA2,TPA3,TPA4,TRPA1,TRPA11,TRPA12,TRPA2,TRPA3,TRPA4
0,gautam,5,0.212639,13,0.103793,0.188616,0.044259,0.070351,0.116575,0.030169,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
1,gautam,5,0.030412,11,0.026436,0.028877,0.028846,0.027433,0.021008,0.029668,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
2,gautam,5,0.109850,39,0.107796,0.107742,0.086027,0.095648,0.127854,0.008424,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
3,gautam,5,0.061227,38,0.021576,0.062308,0.038776,0.053106,0.036498,0.050657,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
4,gautam,5,0.015245,10,0.038250,0.015673,0.010675,0.043753,0.021831,0.015099,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
5,gautam,5,0.000800,8,0.003967,0.000255,0.001628,0.000357,0.001889,0.000478,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
6,gautam,5,0.203975,4,0.089048,0.227372,0.060597,0.037707,0.010828,0.058017,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
7,gautam,5,0.226900,5,0.109448,0.263023,0.058818,0.062147,0.197355,0.029544,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
8,gautam,5,0.250208,27,0.197891,0.181709,0.115160,0.048068,0.100414,0.016023,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
9,gautam,5,0.113421,31,0.177182,0.065856,0.100115,0.119410,0.112940,0.156210,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
10,gautam,5,0.156469,37,0.084170,0.248645,0.175336,0.164495,0.155148,0.068147,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
11,ahilesh,5,0.156186,14,0.149870,0.115835,0.154150,0.124295,0.182222,0.233834,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
12,ahilesh,5,0.093799,20,0.064257,0.167275,0.090034,0.184890,0.198747,0.302923,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
13,ahilesh,5,0.088402,37,0.108088,0.075194,0.139725,0.114361,0.080791,0.126764,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
14,ananay,5,0.018017,38,0.002861,0.055127,0.015706,0.186998,0.026787,0.043183,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
15,ananay,5,0.009851,28,0.022180,0.040108,0.094359,0.027720,0.045067,0.006574,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
16,ananay,5,0.000338,43,0.000451,0.000277,0.000785,0.007004,0.004972,0.000429,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
17,ananay,5,0.033311,27,0.111695,0.091188,0.163318,0.041977,0.142637,0.024349,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
18,ananay,5,0.027616,26,0.029997,0.068907,0.039371,0.008409,0.025155,0.027872,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
19,anish,5,0.101470,28,0.141857,0.081715,0.104424,0.083357,0.096731,0.180990,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
20,anish,5,0.032808,9,0.037739,0.025765,0.005781,0.027664,0.050732,0.051914,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
21,anish,5,0.074773,5,0.064929,0.112701,0.051505,0.097321,0.012824,0.080520,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
22,anish,5,0.212785,6,0.116251,0.066790,0.030495,0.041131,0.056500,0.096626,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
23,anish,5,0.189010,20,0.162033,0.182243,0.144132,0.023218,0.118736,0.009411,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
24,anish,5,0.066572,22,0.050036,0.125059,0.044827,0.068068,0.164678,0.010556,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
25,anish,5,0.108147,37,0.101929,0.135758,0.070784,0.150255,0.134945,0.044119,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
26,anuja,5,0.017799,11,0.008163,0.061911,0.018596,0.043409,0.041552,0.003599,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
27,anuja,5,0.151384,38,0.149214,0.359813,0.302451,0.365638,0.360066,0.019659,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
28,anuja,5,0.007528,16,0.006082,0.019638,0.009101,0.014206,0.014260,0.000964,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
29,anuja,5,0.131851,3,0.093792,0.033768,0.103718,0.018230,0.133619,0.024103,...,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306,257.566306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,bhaswath,5,0.199588,13,0.174928,0.234046,0.147188,0.124348,0.146699,0.238121,...,8.201141,20.479115,6.179668,5.056910,0.215142,0.137152,0.061340,0.226634,0.177905,0.161365
1067,bhaswath,5,0.072825,38,0.059842,0.208130,0.047451,0.149044,0.074878,0.018813,...,10.074038,105.615537,22.904678,9.132376,0.152369,0.107950,0.158987,0.129397,0.191143,0.145540
1068,bhaswath,5,0.023372,10,0.124388,0.058798,0.217881,0.023821,0.085335,0.065744,...,8.107008,9.688063,4.134359,6.895164,0.046748,0.050578,0.115804,0.118834,0.084394,0.217142
1069,bhaswath,5,0.042808,28,0.176062,0.119953,0.102460,0.128726,0.155875,0.041375,...,9.764858,13.083435,5.513320,4.624224,0.040603,0.122334,0.161236,0.197825,0.137862,0.158041
1070,bhaswath,5,0.096240,14,0.108384,0.105598,0.090879,0.203515,0.185513,0.069932,...,5.953670,32.474885,7.361178,3.520333,0.125253,0.222266,0.221342,0.156193,0.157970,0.123513
1071,bhaswath,5,0.046663,15,0.037722,0.161316,0.087872,0.103677,0.056676,0.044676,...,8.158406,40.875141,10.473838,6.496866,0.036261,0.081706,0.053772,0.037441,0.070267,0.066253
1072,bhaswath,5,0.071156,9,0.057019,0.078338,0.056031,0.066976,0.261924,0.003884,...,11.805564,292.038463,40.670559,22.202782,0.123478,0.045502,0.217117,0.116174,0.110312,0.075760
1073,bhaswath,5,0.059792,5,0.030831,0.103611,0.040999,0.103155,0.066709,0.068054,...,10.080564,11.851029,7.977231,6.764318,0.083919,0.107701,0.138275,0.045680,0.143143,0.096854
1074,bhaswath,5,0.059802,41,0.070117,0.234525,0.117171,0.070150,0.025612,0.063068,...,8.062653,48.627366,17.381544,10.091323,0.201084,0.111691,0.061866,0.192125,0.267114,0.178032
1075,bhaswath,5,0.138054,26,0.194398,0.113639,0.095147,0.086044,0.080172,0.066901,...,10.563989,19.417748,9.068034,6.837088,0.123158,0.090803,0.121205,0.194670,0.138138,0.103735
1076,bhaswath,5,0.026992,32,0.017602,0.011404,0.127515,0.029378,0.059159,0.000499,...,8.278689,5453.495703,138.816897,75.995700,0.019323,0.032349,0.052415,0.012079,0.011799,0.067415
1077,bhaswath,5,0.007875,31,0.033622,0.170414,0.159812,0.208148,0.183668,0.017662,...,7.278308,15.560388,4.873271,5.212710,0.013740,0.136387,0.148440,0.026366,0.115104,0.083025
1078,bhaswath,5,0.035382,35,0.023857,0.014910,0.038928,0.085198,0.049346,0.066880,...,14.140774,9.470362,5.901841,4.970662,0.079461,0.192130,0.076398,0.066857,0.099052,0.084863
1079,bhaswath,5,0.103414,20,0.117810,0.133994,0.165296,0.066804,0.062864,0.040486,...,10.607300,102.505000,17.393251,11.194306,0.096752,0.108801,0.136000,0.093545,0.107615,0.154836
1080,bhaswath,5,0.028479,22,0.102889,0.122257,0.075834,0.121502,0.055565,0.026574,...,3.959297,5.433327,6.044941,2.968820,0.063400,0.170436,0.052808,0.056920,0.103090,0.083636
1081,bhaswath,5,0.132032,37,0.079136,0.248811,0.211033,0.139126,0.149426,0.047603,...,11.735386,84.654525,28.129806,10.538567,0.251648,0.154391,0.133165,0.167724,0.269621,0.245752
1082,hrishikesh,5,0.118714,29,0.162708,0.101412,0.152733,0.152782,0.064056,0.072046,...,26.676526,19.031785,12.308475,11.373241,0.250083,0.192410,0.195199,0.256126,0.236980,0.240624
1083,hrishikesh,5,0.044793,16,0.040045,0.147325,0.074255,0.059331,0.373699,0.025832,...,27.640300,157.477480,11.439180,15.862884,0.078781,0.049090,0.220872,0.071327,0.171827,0.089225
1084,hrishikesh,5,0.048836,9,0.028647,0.108525,0.034713,0.011752,0.060781,0.012071,...,19.014800,146.394403,8.272033,17.385180,0.071817,0.020192,0.083794,0.049043,0.107379,0.072914
1085,hrishikesh,5,0.135458,30,0.216146,0.121156,0.184332,0.126615,0.289891,0.338724,...,31.346572,20.330355,12.681983,9.107212,0.126009,0.109475,0.217907,0.129516,0.111340,0.089643
1086,adarsh,5,0.124184,38,0.087456,0.002187,0.064598,0.022966,0.010617,0.101967,...,42.352303,11.533126,6.878129,6.849471,0.171122,0.027412,0.022330,0.050632,0.007272,0.111507
1087,adarsh,5,0.129073,10,0.121752,0.348486,0.057507,0.078315,0.018482,0.028696,...,23.106376,24.795408,10.874245,7.953546,0.148475,0.052284,0.024009,0.131236,0.225992,0.060739
1088,adarsh,5,0.070492,28,0.167331,0.054066,0.158341,0.042031,0.082473,0.096688,...,23.177533,9.595289,10.841220,4.985423,0.162112,0.136888,0.057374,0.194739,0.075697,0.102592
1089,adarsh,5,0.035465,9,0.145032,0.097796,0.117826,0.124597,0.127680,0.023788,...,25.818512,80.745250,10.522469,9.117393,0.093679,0.075825,0.086232,0.127027,0.096710,0.112120
1090,adarsh,5,0.033323,42,0.110228,0.033242,0.070339,0.022629,0.047365,0.009226,...,17.531038,17.274467,20.483274,11.088306,0.088801,0.035364,0.049323,0.218217,0.057221,0.157321
1091,nikhil,5,0.254004,12,0.195086,0.142031,0.199188,0.171014,0.142380,0.117762,...,11.696277,8.242046,5.924918,5.806934,0.235884,0.165102,0.195028,0.257887,0.118789,0.314998
1092,nikhil,5,0.181846,15,0.140251,0.136835,0.150675,0.268452,0.257181,0.068295,...,10.969467,7.778037,6.727844,5.149739,0.158162,0.189421,0.221299,0.129241,0.144340,0.137819
1093,nikhil,5,0.039468,9,0.033839,0.065679,0.035883,0.037765,0.168909,0.008155,...,28.968569,1030.676335,213.089442,200.079931,0.118942,0.036721,0.145236,0.094360,0.159681,0.089902
1094,nikhil,5,0.095570,5,0.072889,0.117442,0.065109,0.007504,0.080361,0.002494,...,9.922443,919.818216,220.800227,163.960116,0.088348,0.025371,0.073689,0.069490,0.106951,0.061634
1095,nikhil,5,0.066995,43,0.081631,0.050094,0.092370,0.153886,0.163210,0.055847,...,22.945730,11.890559,8.006023,6.693655,0.081325,0.170575,0.152727,0.058919,0.077773,0.070208

In [9]:
df[['Question no','hearts','TPA1']][100:200]

     Question no  hearts  TPA1
100            1       4   NaN
101            6       4   NaN
102           33       4   NaN
103           26       4   NaN
104           30       4   NaN
105           34       4   NaN
106           20       4   NaN
107           36       4   NaN
108           23       4   NaN
109           12       4   NaN
110           11       4   NaN
111           38       4   NaN
112           10       4   NaN
113           15       4   NaN
114           17       4   NaN
115            8       4   NaN
116            9       4   NaN
117           42       4   NaN
118           43       4   NaN
119           40       4   NaN
120           33       4   NaN
121           32       4   NaN
122           24       4   NaN
123           36       4   NaN
124           23       4   NaN
125           14       4   NaN
126            9       4   NaN
127           42       4   NaN
128            4       4   NaN
129            7       4   NaN
..           ...     ...   ...
170           27       4   NaN
171           26       4   NaN
172           25       4   NaN
173           11       4   NaN
174           10       4   NaN
175           28       4   NaN
176            4       4   NaN
177            5       4   NaN
178           26       4   NaN
179           25       4   NaN
180           20       4   NaN
181           37       4   NaN
182           42       4   NaN
183           40       4   NaN
184            6       4   NaN
185           27       4   NaN
186           30       4   NaN
187           34       4   NaN
188           36       4   NaN
189           13       4   NaN
190           10       4   NaN
191           28       4   NaN
192           14       4   NaN
193           15       4   NaN
194           42       4   NaN
195            4       4   NaN
196            5       4   NaN
197           43       4   NaN
198           27       4   NaN
199           26       4   NaN

[100 rows x 3 columns]

In [10]:
df=df.fillna(df.mean())

In [11]:
df[['Question no','hearts','TPA1']][100:200]

     Question no  hearts        TPA1
100            1       4  257.566306
101            6       4  257.566306
102           33       4  257.566306
103           26       4  257.566306
104           30       4  257.566306
105           34       4  257.566306
106           20       4  257.566306
107           36       4  257.566306
108           23       4  257.566306
109           12       4  257.566306
110           11       4  257.566306
111           38       4  257.566306
112           10       4  257.566306
113           15       4  257.566306
114           17       4  257.566306
115            8       4  257.566306
116            9       4  257.566306
117           42       4  257.566306
118           43       4  257.566306
119           40       4  257.566306
120           33       4  257.566306
121           32       4  257.566306
122           24       4  257.566306
123           36       4  257.566306
124           23       4  257.566306
125           14       4  257.566306
126            9       4  257.566306
127           42       4  257.566306
128            4       4  257.566306
129            7       4  257.566306
..           ...     ...         ...
170           27       4  257.566306
171           26       4  257.566306
172           25       4  257.566306
173           11       4  257.566306
174           10       4  257.566306
175           28       4  257.566306
176            4       4  257.566306
177            5       4  257.566306
178           26       4  257.566306
179           25       4  257.566306
180           20       4  257.566306
181           37       4  257.566306
182           42       4  257.566306
183           40       4  257.566306
184            6       4  257.566306
185           27       4  257.566306
186           30       4  257.566306
187           34       4  257.566306
188           36       4  257.566306
189           13       4  257.566306
190           10       4  257.566306
191           28       4  257.566306
192           14       4  257.566306
193           15       4  257.566306
194           42       4  257.566306
195            4       4  257.566306
196            5       4  257.566306
197           43       4  257.566306
198           27       4  257.566306
199           26       4  257.566306

[100 rows x 3 columns]

In [12]:
export_csv = df.to_csv(r'/Users/vishwa/Desktop/EEG/data3.csv',index=None,header=True)

In [13]:
import pandas as pd
df = pd.read_csv(r'/Users/vishwa/Desktop/EEG/data2.csv')

In [14]:
df.head()

,name,hearts,TRP1,Question no,TRP2,TRP3,TRP4,TRP11,TRP12,ARP1,...,TPA12,TPA2,TPA3,TPA4,TRPA1,TRPA11,TRPA12,TRPA2,TRPA3,TRPA4
0,gautam,5,0.212639,13,0.103793,0.188616,0.044259,0.070351,0.116575,0.030169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,gautam,5,0.030412,11,0.026436,0.028877,0.028846,0.027433,0.021008,0.029668,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,gautam,5,0.109850,39,0.107796,0.107742,0.086027,0.095648,0.127854,0.008424,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,gautam,5,0.061227,38,0.021576,0.062308,0.038776,0.053106,0.036498,0.050657,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,gautam,5,0.015245,10,0.038250,0.015673,0.010675,0.043753,0.021831,0.015099,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Duplicates have been removed
# Considering the case 
train_data = df.iloc[:516,:]
train_data

,name,hearts,TRP1,Question no,TRP2,TRP3,TRP4,TRP11,TRP12,ARP1,...,TPA12,TPA2,TPA3,TPA4,TRPA1,TRPA11,TRPA12,TRPA2,TRPA3,TRPA4
0,gautam,5,0.212639,13,0.103793,0.188616,0.044259,0.070351,0.116575,0.030169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,gautam,5,0.030412,11,0.026436,0.028877,0.028846,0.027433,0.021008,0.029668,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,gautam,5,0.109850,39,0.107796,0.107742,0.086027,0.095648,0.127854,0.008424,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,gautam,5,0.061227,38,0.021576,0.062308,0.038776,0.053106,0.036498,0.050657,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,gautam,5,0.015245,10,0.038250,0.015673,0.010675,0.043753,0.021831,0.015099,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,gautam,5,0.000800,8,0.003967,0.000255,0.001628,0.000357,0.001889,0.000478,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,gautam,5,0.203975,4,0.089048,0.227372,0.060597,0.037707,0.010828,0.058017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,gautam,5,0.226900,5,0.109448,0.263023,0.058818,0.062147,0.197355,0.029544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,gautam,5,0.250208,27,0.197891,0.181709,0.115160,0.048068,0.100414,0.016023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,gautam,5,0.113421,31,0.177182,0.065856,0.100115,0.119410,0.112940,0.156210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,gautam,5,0.156469,37,0.084170,0.248645,0.175336,0.164495,0.155148,0.068147,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,ahilesh,5,0.156186,14,0.149870,0.115835,0.154150,0.124295,0.182222,0.233834,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,ahilesh,5,0.093799,20,0.064257,0.167275,0.090034,0.184890,0.198747,0.302923,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,ahilesh,5,0.088402,37,0.108088,0.075194,0.139725,0.114361,0.080791,0.126764,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,ananay,5,0.018017,38,0.002861,0.055127,0.015706,0.186998,0.026787,0.043183,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,ananay,5,0.009851,28,0.022180,0.040108,0.094359,0.027720,0.045067,0.006574,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,ananay,5,0.000338,43,0.000451,0.000277,0.000785,0.007004,0.004972,0.000429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,ananay,5,0.033311,27,0.111695,0.091188,0.163318,0.041977,0.142637,0.024349,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,ananay,5,0.027616,26,0.029997,0.068907,0.039371,0.008409,0.025155,0.027872,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,anish,5,0.101470,28,0.141857,0.081715,0.104424,0.083357,0.096731,0.180990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,anish,5,0.032808,9,0.037739,0.025765,0.005781,0.027664,0.050732,0.051914,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,anish,5,0.074773,5,0.064929,0.112701,0.051505,0.097321,0.012824,0.080520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,anish,5,0.212785,6,0.116251,0.066790,0.030495,0.041131,0.056500,0.096626,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,anish,5,0.189010,20,0.162033,0.182243,0.144132,0.023218,0.118736,0.009411,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,anish,5,0.066572,22,0.050036,0.125059,0.044827,0.068068,0.164678,0.010556,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,anish,5,0.108147,37,0.101929,0.135758,0.070784,0.150255,0.134945,0.044119,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,anuja,5,0.017799,11,0.008163,0.061911,0.018596,0.043409,0.041552,0.003599,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,anuja,5,0.151384,38,0.149214,0.359813,0.302451,0.365638,0.360066,0.019659,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,anuja,5,0.007528,16,0.006082,0.019638,0.009101,0.014206,0.014260,0.000964,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,anuja,5,0.131851,3,0.093792,0.033768,0.103718,0.018230,0.133619,0.024103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,atul,1,0.117115,23,0.147855,0.178465,0.226753,0.169579,0.276255,0.023579,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,atul,1,0.116478,37,0.217435,0.125414,0.239521,0.072734,0.216465,0.129648,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488,bhargavi,1,0.164606,12,0.136226,0.176634,0.106181,0.130821,0.089236,0.018645,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489,bhargavi,1,0.117165,39,0.117309,0.106141,0.120371,0.114435,0.286229,0.005637,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
490,bhargavi,1,0.121908,38,0.127564,0.075009,0.071413,0.079515,0.059899,0.015596,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
491,bhargavi,1,0.265222,14,0.103853,0.329260,0.059319,0.063397,0.076485,0.025760,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
492,bhargavi,1,0.141147,17,0.131755,0.189316,0.140961,0.108613,0.400690,0.011824,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,bhargavi,1,0.077201,1,0.093357,0.068421,0.088363,0.066969,0.099539,0.026160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,bhargavi,1,0.085041,7,0.064327,0.120040,0.045942,0.046232,0.090381,0.002938,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,bhargavi,1,0.159799,24,0.159236,0.144872,0.151749,0.145659,0.245739,0.011877,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,bhargavi,1,0.159110,31,0.161220,0.172584,0.177249,0.218296,0.168757,0.010988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,bhargavi,1,0.160384,21,0.163339,0.088645,0.155427,0.018888,0.114457,0.003029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,bhargavi,1,0.068535,22,0.053330,0.111727,0.047886,0.073543,0.124840,0.008540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,bhargavi,1,0.029387,23,0.020796,0.032296,0.014179,0.021352,0.129390,0.001851,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500,bhaswath,1,0.063341,11,0.059274,0.059396,0.048968,0.065747,0.052751,0.002324,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
501,bhaswath,1,0.101694,17,0.068183,0.107995,0.111696,0.062559,0.206269,0.012370,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502,bhaswath,1,0.059408,16,0.042314,0.070556,0.045501,0.158850,0.098979,0.065466,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
503,hrishikesh,1,0.241140,8,0.213505,0.240942,0.101947,0.231490,0.058890,0.065250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,hrishikesh,1,0.022110,2,0.036313,0.018801,0.088483,0.065326,0.016688,0.071042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505,adarsh,1,0.070999,13,0.051186,0.153626,0.116487,0.085848,0.029744,0.016512,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,adarsh,1,0.359976,17,0.205342,0.113891,0.069282,0.282937,0.098070,0.103041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
507,adarsh,1,0.126679,8,0.043551,0.056412,0.054916,0.046875,0.019041,0.034179,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
508,adarsh,1,0.058315,3,0.109803,0.151243,0.072111,0.008991,0.026633,0.029606,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
509,adarsh,1,0.068062,1,0.013005,0.072921,0.067611,0.061994,0.303221,0.049529,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510,adarsh,1,0.075109,18,0.030491,0.039393,0.101848,0.057172,0.075134,0.051210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
511,nikhil,1,0.365480,39,0.292549,0.187005,0.326578,0.028082,0.242704,0.078341,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,nikhil,1,0.162776,8,0.116096,0.181500,0.086825,0.282772,0.124221,0.047734,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513,nikhil,1,0.039314,3,0.019166,0.081914,0.013261,0.080337,0.050088,0.017147,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
514,nikhil,1,0.129080,25,0.088548,0.152612,0.086030,0.100551,0.082819,0.065982,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
515,nikhil,1,0.094704,36,0.083580,0.094740,0.102734,0.101272,0.103684,0.014948,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# since our data is not in similar range, Eg: Question No. and TRP2
# Normalizing the data

# Standard normalization using the data
# We do not need the data of everyone while processing

# NAN values have been eliminated


X = train_data.iloc[:,2:21]
Y = train_data.iloc[:,1]

In [17]:
X.head()

,TRP1,Question no,TRP2,TRP3,TRP4,TRP11,TRP12,ARP1,ARP2,ARP3,ARP4,ARP11,ARP12,BRP1,BRP2,BRP3,BRP4,BRP11,BRP12
0,0.212639,13,0.103793,0.188616,0.044259,0.070351,0.116575,0.030169,0.018603,0.027909,0.019561,0.010856,0.068287,0.002027,0.002052,0.003781,0.013086,0.002404,0.034083
1,0.030412,11,0.026436,0.028877,0.028846,0.027433,0.021008,0.029668,0.027854,0.017562,0.026729,0.014464,0.021211,0.015660,0.007382,0.011380,0.014429,0.012758,0.009552
2,0.109850,39,0.107796,0.107742,0.086027,0.095648,0.127854,0.008424,0.009106,0.010126,0.015019,0.029904,0.076563,0.001016,0.001579,0.002597,0.005626,0.011823,0.047868
3,0.061227,38,0.021576,0.062308,0.038776,0.053106,0.036498,0.050657,0.017930,0.068747,0.041289,0.161568,0.060074,0.032662,0.010209,0.068815,0.042211,0.096338,0.025203
4,0.015245,10,0.038250,0.015673,0.010675,0.043753,0.021831,0.015099,0.065463,0.014150,0.048185,0.045156,0.117432,0.014204,0.026668,0.012522,0.019465,0.020016,0.023847

In [18]:
# Clustering into 3 ratings

#for i in Y:
    #if i==1 or i==2:
        #i = 1
    #elif i==4 or i==5:
        #i = 5
    #else:
        #i=3

In [19]:
Y.head()

0    5
1    5
2    5
3    5
4    5
Name: hearts, dtype: int64

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() 
# using mean/ standard deviation for normalization
X= scaler.fit_transform(X)

# till BRP 12 we have all values so will only be considering those
# first we need to split the data
# 5 class or 3 class classification - CONFIRM

# ritchieng.com/machine-learning-k-nearest-neighbors-knn/

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/anaconda3/lib/python3.7/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [21]:
# Applying K-Nearest Neighbours Algorithm
# Iterating for different values of K
# Training on the entire set to find the correct value of K 
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier


knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X,Y)
Y_pred = knn.predict(X)
# to evaluate the accuracy of the model
print(metrics.accuracy_score(Y, Y_pred))

0.5794573643410853

In [22]:
# Applying Random Forests Classifier
# https://towardsdatascience.com/an-implementation-and-explanation-of-the-random-forest-in-python-77bf308a9b76

from sklearn.ensemble import RandomForestClassifier

# Creating a Random Foresr with 100 trees
model = RandomForestClassifier(n_estimators=100,bootstrap=True,max_features ='sqrt')

model.fit(X,Y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [32]:
# Actual Predcitons
Y_pred = model.predict(X)
# Predictions for each class
Y_probs = model.predict_proba(X)

print(Y_pred)
print(Y_probs)

[5 5 5 5 5 5 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 3 5 5 5 5 5 5 5 5 5 5 4 4 4 4 4 4 4 4 1 4 4 4
 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 3 4 4 4 4 1 4 4 4 4 4 2 4 4 4 4 4 4 4 4 3 3 5 4 4 4 4 4 4 4 4 4 4
 4 4 4 5 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 5 3 4 4 4 4 4 4 4 4 4
 4 4 4 2 3 3 5 3 3 3 3 3 3 3 4 3 3 3 3 5 4 3 3 1 3 3 3 4 3 3 3 3 3 3 3 3 3
 3 3 1 3 3 4 3 4 3 3 3 3 3 3 3 3 3 3 5 5 3 4 2 3 3 3 3 3 3 4 3 3 3 3 3 3 3
 3 3 3 5 3 3 3 3 4 3 3 3 3 3 4 3 3 3 3 3 4 4 5 5 3 3 3 3 3 3 3 2 3 5 3 3 2
 3 2 2 3 3 3 3 3 3 3 3 3 4 3 3 3 3 2 3 3 3 1 3 3 3 3 2 2 2 2 2 2 2 2 2 3 2
 2 2 4 2 2 2 2 2 4 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 1 2
 2 2 2 2 2 2 2 2 5 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 4 2 2 3 2
 2 2 4 2 2 2 2 2 1 1 1 1 1 1 3 1 1 1 1 1 4 3 1 1 1 4 1 1 1 1 5 1 4 1 1 1 1
 1 3 3 1 1 1 3 1 1 1 1 1 1 1 2 1 5 1 1 1 2 1 1 1 5 1 1 1 1 1 1 1 1 1 1]
[[0.1  0.03 0.1  0.1  0.67]
 [0.16 0.06 0.25 0.17 0.36]
 [0.12 0.05 0.04 0.06 0.73]
 ...
 [0.75 0.05 0.08 0.07 0.05]
 [0.58 0.05 0.14 0.14 0.09]
 [0.68 0.03 0.12 0.1  0.07]]

In [33]:
# After Training on the entire data
# We are training on the entire data so that we can tune the parameters
print(metrics.accuracy_score(Y, Y_pred))

0.8546511627906976

In [34]:
# Creating a test train split

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20,random_state=10)

In [35]:
model.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [36]:
Y_pred = model.predict(X_test)
Y_probs = model.predict_proba(X_test)[:,1]
print(metrics.accuracy_score(Y_test, Y_pred))

0.28846153846153844

In [39]:
# Using Decision tree

rf = RandomForestClassifier( max_depth=10,random_state=7) 
rf.fit(X_train, Y_train)
sc_train = rf.score(X_train,Y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [38]:
sc_train

0.9199029126213593